# Site settings
title: ACApi
email: dan.thomas@dc.gov
description: "The Affordable Care Act API (ACApi) is a flexible IT architecture framework that enables agencies to rapidly establish and extend cost-effective, online health insurance marketplaces for individuals and small businesses"
baseurl: ""
url: "http://acapi.dchbx.org"
twitter_username: danjthomas
github_username:  dchbx

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
permalink: pretty
